spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.3.38.49:3306/prod_workflow
spring.datasource.username=murthy_workflow
spring.datasource.password=M!rthW0rk#Flow@2026X

spring.jpa.hibernate.ddl-auto=validate
spring.datasource.hikari.maximum-pool-size=20

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

storage.file.directory.location=/home/metaverseedu/public_html/workflowfiles-temp/

tihcl.userName=executive1@gmail.com
tihcl.password=Password@123
