spring:
  application:
    name: workflow

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      auto-startup: true
    consumer:
      group-id: email-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring.mail.username:#{secrets['spring.mail.username']}}
    password: ${spring.mail.password:#{secrets['spring.mail.password']}}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.3.38.49:3306/prod_workflow
    hikari:
      maximum-pool-size: 20

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          fetch_size: 500
          batch_size: 500
    hibernate:
      ddl-auto: validate

  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB

  jackson:
    date-format: dd-MM-yyyy
    time-zone: Asia/Kolkata
    serialization:
      write-dates-as-timestamps: false

  security:
    enabled: true

  config:
    import:
      - vault://
      - "optional:classpath:secrets.properties"

  cloud:
    vault:
      host: 10.3.38.49
      port: 9090
      scheme: http
      authentication: TOKEN
      token: ${VAULT_TOKEN:#{secrets['VAULT_TOKEN']}}
      config:
        order: -10
      kv:
        enabled: true
        backend: secret
        default-context: workflow
        profile-separator: "-"

server:
  port: 8081
  servlet:
    context-path: /workflow
    session:
      timeout: 5m
  error:
    include-message: always
    include-stacktrace: on_param
    include-exception: true
    include-binding-errors: always

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui
    url: /api/v3/api-docs
    enabled: true
  swagger:
    permitted-paths: /api/swagger-ui/**,/api/swagger-ui.html,/api/v3/api-docs/**
    enabled: true

storage:
  file:
    directory:
      location: ${storage.file.directory.location:/opt/workflow/uploads}

jwt:
  secret: ${jwt.secret:#{secrets['jwt.secret']}}
  expiration: 86400000

cors:
  allowed-origins: https://tg.ramp.metaversedu.in,http://localhost:*,http://127.0.0.1:3000,http://127.0.0.1:4200,http://10.3.38.49,http://10.3.38.49:3000

logging:
  level:
    org.hibernate.orm.connections.pooling: WARN
    org.hibernate.orm.deprecation: WARN