
-- Insert program outcome tables
insert into program_outcome_tables (outcome_table_id, outcome_table_display_name, outcome_table_name) values
(1, 'ONDC Registration', 'ONDCRegistration'),
(2, 'ONDC Transaction', 'ONDCTransaction'),
(3, 'Udyam Registration', 'UdyamRegistration'),
(4, 'CGTMSE Transaction', 'CGTMSETransaction'),
(5, 'GeM Transaction','GeMTransaction'),
(6,'TReDS Registration','TReDSRegistration'),
(7,'TReDS Transaction','TReDSTransaction'),
(8,'PMEGP','PMEGP'),
(9,'PMMY','PMMY'),
(10,'PMS','PMS'),
(11, 'IC Scheme', 'ICScheme'),
(12,'NSIC','NSIC'),
(13,'Patents','Patents'),
(14,'GIProduct','GIProduct'),
(15,'Barcode','Barcode'),
(16,'TreadMark','TreadMark'),
(17,'ZEDCertification Bronze','ZEDCertificationBronze'),
(18,'ZEDCertification Silver','ZEDCertificationSilver'),
(19,'ZEDCertification Gold','ZEDCertificationGold'),
(20,'Lean','Lean'),
(21,'PM Viswakarma','PMViswakarma'),
(22,'Vendor Development','VendorDevelopment'),
(23,'Sc St Hub','ScStHub'),
(24,'SIDBI Aspire','SIDBIAspire'),
(25,'GeM Registration','GeMRegistration'),
(26,'OEM','OEM'),
(27,'PMFME Scheme','PMFMEScheme'),
(28,'Consortia & Tender Marketing','ConsortiaTender'),
(29,'Design Right','DesignRight')
(30,'Copy Right','CopyRight'),
(31,'Greening Of MSME','GreeningOfMSME');

